FROM node:20-alpine AS builder
WORKDIR /app

RUN corepack enable

ARG VITE_STATIC_URL=/static/
ARG VITE_VDITOR_CDN=/vditor
ARG VITE_SITE_ICP=
ARG VITE_SITE_ICP_LINK=
ARG VITE_SITE_NAME=xs-blog
ARG VITE_GITHUB_REPO=xs-blog
ARG VITE_GITHUB_REPO_URL=#
ARG VITE_BACKEND_BASE_URL=
ARG VITE_BACKEND_STATIC=static

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
ENV VITE_STATIC_URL=${VITE_STATIC_URL}
ENV VITE_VDITOR_CDN=${VITE_VDITOR_CDN}
ENV VITE_SITE_ICP=${VITE_SITE_ICP}
ENV VITE_SITE_ICP_LINK=${VITE_SITE_ICP_LINK}
ENV VITE_SITE_NAME=${VITE_SITE_NAME}
ENV VITE_GITHUB_REPO=${VITE_GITHUB_REPO}
ENV VITE_GITHUB_REPO_URL=${VITE_GITHUB_REPO_URL}
ENV VITE_BACKEND_BASE_URL=${VITE_BACKEND_BASE_URL}
ENV VITE_BACKEND_STATIC=${VITE_BACKEND_STATIC}
RUN pnpm build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
